#!/bin/bash
title="Select example"
prompt="Pick an option:"
options=("On-Demand " "Performance " "Powersave")
echo "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do 

    case "$REPLY" in
 
    1 ) echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;;
    2 ) echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;;
    3 ) echo powersave > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;;

    $(( ${#options[@]}+1 )) ) echo "Goodbye!"; break;;
     *) echo "Invalid option. Try another one.";continue;;
   
     esac

done
